# Generated by dbc::update_drivers() — do not edit by hand.
# Source: dbc search  (2026-05-15 07:07:17.492894)

#' DBI-compatible driver for 'bigquery' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("bigquery"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
bigquery <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("bigquery"))
}

#' DBI-compatible driver for 'clickhouse' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("clickhouse"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
clickhouse <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("clickhouse"))
}

#' DBI-compatible driver for 'databricks' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("databricks"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
databricks <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("databricks"))
}

#' DBI-compatible driver for 'duckdb' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("duckdb"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
duckdb <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("duckdb"))
}

#' DBI-compatible driver for 'exasol' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("exasol"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
exasol <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("exasol"))
}

#' DBI-compatible driver for 'flightsql' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("flightsql"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
flightsql <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("flightsql"))
}

#' DBI-compatible driver for 'mssql' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("mssql"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
mssql <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("mssql"))
}

#' DBI-compatible driver for 'mysql' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("mysql"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
mysql <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("mysql"))
}

#' DBI-compatible driver for 'postgresql' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("postgresql"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
postgresql <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("postgresql"))
}

#' DBI-compatible driver for 'redshift' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("redshift"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
redshift <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("redshift"))
}

#' DBI-compatible driver for 'singlestore' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("singlestore"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
singlestore <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("singlestore"))
}

#' DBI-compatible driver for 'snowflake' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("snowflake"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
snowflake <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("snowflake"))
}

#' DBI-compatible driver for 'sqlite' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("sqlite"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
sqlite <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("sqlite"))
}

#' DBI-compatible driver for 'trino' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("trino"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
trino <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("trino"))
}

#' DBI-compatible driver for 'oracle' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("oracle"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
oracle <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("oracle"))
}

#' DBI-compatible driver for 'sap-hana' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("sap-hana"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
sap_hana <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("sap-hana"))
}

#' DBI-compatible driver for 'teradata' via ADBC
#'
#' Equivalent to \code{adbi::adbi(adbcdrivermanager::adbc_driver("teradata"))}.
#' The driver is installed automatically when \code{getOption("dbc.autoinstall")}
#' is \code{TRUE} (the default).
#'
#' @return An \code{AdbiDriver} object for use with [DBI::dbConnect()].
#' @export
teradata <- function() {
  if (!requireNamespace("adbi", quietly = TRUE)) {
    stop("Package 'adbi' is required. Install it with install.packages('adbi').")
  }
  if (!requireNamespace("adbcdrivermanager", quietly = TRUE)) {
    stop("Package 'adbcdrivermanager' is required. Install it with install.packages('adbcdrivermanager').")
  }
  adbi::adbi(load_driver("teradata"))
}

