#' Regenerate driver helper functions from the dbc registry
#'
#' Queries the registry (via [dbc_search()]), then writes
#' \file{R/drivers-generated.R} with one DBI driver constructor per available
#' driver that does not already have a hand-written file in \file{R/drivers/}.
#' Also updates \file{NAMESPACE} to export every generated function.
#'
#' This is a developer/maintainer tool — run it, review the diff, and commit
#' the result.  It is also used by CI to detect when new drivers have been
#' published and a package update is needed.
#'
#' @param pkg Path to the package root. Defaults to the current directory.
#' @return Invisibly returns a character vector of driver names that were
#'   generated (excludes hand-written drivers).
update_drivers <- function(pkg = ".") {
  drivers <- dbc_search("")
  if (length(drivers) == 0L) stop("dbc registry returned no drivers")

  # Produce a valid R identifier from a driver path like "adbc-sqlite" or
  # "org/snowflake".  Keep only alphanumeric + underscore, replace everything
  # else with underscore, strip leading underscores.
  fn_name <- function(path) {
    nm <- gsub("[^A-Za-z0-9_]", "_", path)
    nm <- sub("^_+", "", nm)
    nm
  }

  # Skip drivers that already have a hand-written file in R/.
  # Hand-written driver files are named after the R function (e.g. snowflake.R).
  # We exclude non-driver files by checking against the known generated names.
  hand_written <- sub("\\.R$", "", list.files(file.path(pkg, "R"),
                                              pattern = "\\.R$"))
  all_names    <- fn_name(drivers)
  to_generate  <- drivers[!all_names %in% hand_written]

  lines <- c(
    "# Generated by dbc::update_drivers() — do not edit by hand.",
    paste0("# Source: dbc search  (", Sys.time(), ")"),
    if (length(to_generate) == 0L)
      "# All drivers currently have hand-written implementations in R/drivers/."
    else
      NULL,
    ""
  )

  for (path in to_generate) {
    nm <- fn_name(path)
    lines <- c(lines,
      paste0("#' DBI-compatible driver for '", path, "' via ADBC"),
      "#'",
      paste0("#' Equivalent to \\code{adbi::adbi(adbcdrivermanager::adbc_driver(\"", path, "\"))}."),
      "#' The driver is installed automatically when \\code{getOption(\"dbc.autoinstall\")}",
      "#' is \\code{TRUE} (the default).",
      "#'",
      "#' @return An \\code{AdbiDriver} object for use with [DBI::dbConnect()].",
      "#' @export",
      paste0(nm, " <- function() {"),
      paste0("  adbi::adbi(load_driver(\"", path, "\"))"),
      "}",
      ""
    )
  }

  out_r <- file.path(pkg, "R", "drivers-generated.R")
  writeLines(lines, out_r)
  message("Wrote ", out_r)

  # Rewrite NAMESPACE — preserve non-export lines, replace all export() lines
  # that correspond to generated names, then add any new ones.
  ns_path <- file.path(pkg, "NAMESPACE")
  ns <- readLines(ns_path)

  generated_names <- fn_name(to_generate)

  # Remove existing exports for generated names
  is_generated_export <- grepl("^export\\(", ns) &
    vapply(ns, function(line) {
      m <- regmatches(line, regexpr("(?<=export\\().*(?=\\))", line, perl = TRUE))
      length(m) > 0 && m %in% generated_names
    }, logical(1L))
  ns <- ns[!is_generated_export]

  # Insert generated exports after the last non-generated export line
  export_lines <- paste0("export(", generated_names, ")")
  last_export <- max(c(0L, which(grepl("^export\\(", ns))))
  ns <- c(
    ns[seq_len(last_export)],
    export_lines,
    if (last_export < length(ns)) ns[seq(last_export + 1L, length(ns))]
  )

  writeLines(ns, ns_path)
  message("Updated ", ns_path)

  invisible(to_generate)
}
